apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-root-password: %MYSQL_ROOT_PASSWORD
  mysql-user: %MYSQL_USER
  mysql-password: %MYSQL_PASSWORD
  mysql-database-connection: %DATABASE_CONNECTION

